# Generated by Django 3.2.13 on 2024-07-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240722_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verifird_email',
            new_name='is_verified_email',
        ),
    ]
