# Generated by Django 3.2.13 on 2024-07-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукт'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'категории', 'verbose_name_plural': 'Категории'},
        ),
    ]
